version: '3.8'

services:
  nginx:
    build:
      context: ./docker/nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/symfony
    depends_on:
      - php

  php:
    build:
      context: ./docker/php
    volumes:
      - ./src:/var/www/symfony
    depends_on:
      - mysql

  mysql:
    build:
      context: ./docker/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
